### ISSUE TITLE
Multiple headings of level one on the same page

### ISSUE THREAD

**Issue by holistic-developer** [cloud-native-austria/kcd-austria-website#55]
To have better accessibility, the page should only have one heading of level 1 on any page.
The sizing of the text should be achieved by updating the tailwind config.

```[tasklist]
### Tasks
- [x] Check all pages and change HTML to only have one h1
- [x] Make sure other header levels are nested correctly h1 → h2 → h3 ...
- [x] Update styles to match previous sizing of the headings
```
